
# function(getToolchainByArch target outClang outClangxx outSysroot outLibExtension)
#     if ("${target}" STREQUAL "android-aarch64")
#         set(${outClang} "${ANDROID_TOOLCHAIN_ROOT}/bin/aarch64-linux-android${ANDROID_VERSION}-clang")
#         set(${outClangxx} "${outClang}++")
#         set(${outSysroot} "${ANDROID_SYSROOT}")
#         set(${outLibExtension} "so")
#     elseif ("${target}" STREQUAL "android-armv7a")
#         set(${outClang} "${ANDROID_TOOLCHAIN_ROOT}/bin/armv7a-linux-androideabi${ANDROID_VERSION}-clang")
#         set(${outClangxx} "${outClang}++")
#         set(${outSysroot} "${ANDROID_SYSROOT}")
#         set(${outLibExtension} "so")
#     elseif ("${target}" STREQUAL "android-i686")
#         set(${outClang} "${ANDROID_TOOLCHAIN_ROOT}/bin/i686-linux-android${ANDROID_VERSION}-clang")
#         set(${outClangxx} "${outClang}++")
#         set(${outSysroot} "${ANDROID_SYSROOT}")
#         set(${outLibExtension} "so")
#     elseif ("${target}" STREQUAL "android-x86_64")
#         set(${outClang} "${ANDROID_TOOLCHAIN_ROOT}/bin/x86_64-linux-android${ANDROID_VERSION}-clang")
#         set(${outClangxx} "${outClang}++")
#         set(${outSysroot} "${ANDROID_SYSROOT}")
#         set(${outLibExtension} "so")
#     elseif ("${target}" STREQUAL "local")
#         set(${outClang} "clang")
#         set(${outClangxx} "clang++")
#         set(${outSysroot} "/")
#         if ("${BUILD_HOST}" STREQUAL "linux")
#             set(${outLibExtension} "so")
#         else()
#             set(${outLibExtension} "dylib")
#         endif()
#     endif()
# endfunction()

# set(BUILD_TARGETS ${ANDROID_BUILD_TARGETS})
# list(PREPEND BUILD_TARGETS "local")

# if ("${BUILD_HOST}" STREQUAL "darwin")
#     list(APPEND BUILD_TARGETS ${IOS_BUILD_TARGETS})
# endif()
